<?php
/**
 * @file
 * Code for the JDT Content Type Article feature.
 */

/**
 * Creates Date Format Title.
 */
function jdt_content_type_article_date_format_types() {
  $type = 'jdt_content_type_article_time';
  $format = 'F j, Y';

  variable_set('date_format_' . $type, $format);

  return array(
    'jdt_content_type_article_time' => t('JDT Views'),
  );
}

include_once 'jdt_content_type_article.features.inc';